server:
  port: 8090
  servlet:
    context-path: /api/v1

spring:
  application:
    name: price-tracker-app
  # Configure datasource for development with PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/price_tracker_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Change to validate once using Liquibase properly
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  # Liquibase Configuration
  liquibase:
    enabled: false # Set to true once you have changelog files
    change-log: classpath:db/changelog/db.changelog-master.xml
  # Mail Configuration (for price alerts)
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  # ThymeLeaf Configuration
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

# Logging Configuration
logging:
  level:
    root: INFO
    com.pricetracker.app: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

# App-specific configurations
app:
  base-url: http://localhost:8090/api/v1
  scheduling:
    checkRateMs: 60000  # 1 minute in milliseconds (scheduler frequency)
  scraper:
    default-delay-ms: 3000  # Increased to 3 seconds delay between requests
    user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"  # More realistic user agent
  notification:
    cooldown-hours: 24  # Set a 24-hour cooldown between notifications for the same product/user

# JWT Configuration
api:
  jwt:
    secret-key: VeryLongSecretKeyForJwtSigningThatIsAtLeastThirtyTwoCharactersLong0123456789
    access-token-expiration-ms: 3600000  # 1 hour
    refresh-token-expiration-ms: 604800000  # 7 days

# Additional JWT configuration used by RefreshTokenServiceImpl
jwt:
  secret: VeryLongSecretKeyForJwtSigningThatIsAtLeastThirtyTwoCharactersLong0123456789
  expiration: 3600000  # 1 hour
  refresh-token:
    expiration: 604800000  # 7 days
    storage: database

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Content-Type
    - X-Requested-With
  max-age: 3600

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true 